version: '3.7'
name: 'thullo'
services:
  postgres:
    image: postgres:14
    container_name: 'db'
    restart: always
    environment:
      - POSTGRES_DB=thullo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
    mem_reservation: '10M'
    mem_limit: '250M'
    ports:
      - '5434:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: 'redis'
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
volumes:
  cache:
    driver: local
