version: '3.8'

services:
  db:
    container_name: thullo_postgress
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
